/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PosterDesignerRouteImport } from './routes/poster-designer'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OrderProductRouteImport } from './routes/order.$product'
import { Route as AdminSuppliersRouteImport } from './routes/admin.suppliers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminExpensesRouteImport } from './routes/admin.expenses'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterDesignerRoute = PosterDesignerRouteImport.update({
  id: '/poster-designer',
  path: '/poster-designer',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OrderProductRoute = OrderProductRouteImport.update({
  id: '/order/$product',
  path: '/order/$product',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExpensesRoute = AdminExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/poster-designer': typeof PosterDesignerRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/track': typeof TrackRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/order/$product': typeof OrderProductRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/poster-designer': typeof PosterDesignerRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/track': typeof TrackRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/order/$product': typeof OrderProductRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/poster-designer': typeof PosterDesignerRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/track': typeof TrackRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/order/$product': typeof OrderProductRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/how-it-works'
    | '/order-confirmation'
    | '/poster-designer'
    | '/pricing'
    | '/products'
    | '/track'
    | '/admin/activity'
    | '/admin/customers'
    | '/admin/expenses'
    | '/admin/inventory'
    | '/admin/invoices'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/suppliers'
    | '/order/$product'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/how-it-works'
    | '/order-confirmation'
    | '/poster-designer'
    | '/pricing'
    | '/products'
    | '/track'
    | '/admin/activity'
    | '/admin/customers'
    | '/admin/expenses'
    | '/admin/inventory'
    | '/admin/invoices'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/suppliers'
    | '/order/$product'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/how-it-works'
    | '/order-confirmation'
    | '/poster-designer'
    | '/pricing'
    | '/products'
    | '/track'
    | '/admin/activity'
    | '/admin/customers'
    | '/admin/expenses'
    | '/admin/inventory'
    | '/admin/invoices'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/suppliers'
    | '/order/$product'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  HowItWorksRoute: typeof HowItWorksRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  PosterDesignerRoute: typeof PosterDesignerRoute
  PricingRoute: typeof PricingRoute
  ProductsRoute: typeof ProductsRoute
  TrackRoute: typeof TrackRoute
  OrderProductRoute: typeof OrderProductRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster-designer': {
      id: '/poster-designer'
      path: '/poster-designer'
      fullPath: '/poster-designer'
      preLoaderRoute: typeof PosterDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/order/$product': {
      id: '/order/$product'
      path: '/order/$product'
      fullPath: '/order/$product'
      preLoaderRoute: typeof OrderProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/expenses': {
      id: '/admin/expenses'
      path: '/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AdminExpensesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminExpensesRoute: typeof AdminExpensesRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminExpensesRoute: AdminExpensesRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  HowItWorksRoute: HowItWorksRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  PosterDesignerRoute: PosterDesignerRoute,
  PricingRoute: PricingRoute,
  ProductsRoute: ProductsRoute,
  TrackRoute: TrackRoute,
  OrderProductRoute: OrderProductRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
